"""initial_schema

Revision ID: 70fc590d8a42
Revises: 
Create Date: 2026-09-14 16:47:54.583512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.spatial


# revision identifiers, used by Alembic.
revision: str = '70fc590d8a42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environmental_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('wind_direction', sa.Float(), nullable=False),
    sa.Column('current_u', sa.Float(), nullable=False),
    sa.Column('current_v', sa.Float(), nullable=False),
    sa.Column('wave_height', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('geometry', app.db.spatial.GeoJSONGeometry(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmental_data_id'), 'environmental_data', ['id'], unique=False)
    op.create_index(op.f('ix_environmental_data_timestamp'), 'environmental_data', ['timestamp'], unique=False)
    op.create_table('satellite_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('satellite', sa.String(length=100), nullable=False),
    sa.Column('sensor', sa.String(length=100), nullable=False),
    sa.Column('acquisition_time', sa.DateTime(), nullable=False),
    sa.Column('polarization', sa.String(length=50), nullable=False),
    sa.Column('orbit', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('bounding_geometry', app.db.spatial.GeoJSONGeometry(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellite_images_acquisition_time'), 'satellite_images', ['acquisition_time'], unique=False)
    op.create_index(op.f('ix_satellite_images_id'), 'satellite_images', ['id'], unique=False)
    op.create_index(op.f('ix_satellite_images_product_id'), 'satellite_images', ['product_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vessels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mmsi', sa.String(length=20), nullable=False),
    sa.Column('imo', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('ship_type', sa.String(length=80), nullable=False),
    sa.Column('flag', sa.String(length=80), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessels_id'), 'vessels', ['id'], unique=False)
    op.create_index(op.f('ix_vessels_imo'), 'vessels', ['imo'], unique=False)
    op.create_index(op.f('ix_vessels_mmsi'), 'vessels', ['mmsi'], unique=True)
    op.create_table('ais_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('position', app.db.spatial.GeoJSONGeometry(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('course', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('navigation_status', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ais_timestamp', 'ais_positions', ['timestamp'], unique=False)
    op.create_index('idx_ais_vessel_timestamp', 'ais_positions', ['vessel_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_ais_positions_id'), 'ais_positions', ['id'], unique=False)
    op.create_index(op.f('ix_ais_positions_timestamp'), 'ais_positions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ais_positions_vessel_id'), 'ais_positions', ['vessel_id'], unique=False)
    op.create_table('spill_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('satellite_image_id', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('area_km2', sa.Float(), nullable=False),
    sa.Column('perimeter_km', sa.Float(), nullable=False),
    sa.Column('centroid', app.db.spatial.GeoJSONGeometry(), nullable=True),
    sa.Column('bounding_box', app.db.spatial.GeoJSONGeometry(), nullable=True),
    sa.Column('spill_geometry', app.db.spatial.GeoJSONGeometry(), nullable=False),
    sa.Column('status', sa.Enum('NOT_ANALYZED', 'ANALYZING', 'DETECTED', 'NO_SPILL', 'REVIEW_REQUIRED', 'ACCEPTED', 'REJECTED', name='spillstatus'), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['satellite_image_id'], ['satellite_images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spill_events_detected_at'), 'spill_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_spill_events_id'), 'spill_events', ['id'], unique=False)
    op.create_index(op.f('ix_spill_events_status'), 'spill_events', ['status'], unique=False)
    op.create_table('drift_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spill_event_id', sa.Integer(), nullable=False),
    sa.Column('simulation_type', sa.Enum('FORWARD', 'BACKWARD', name='simulationtype'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('particle_count', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='simulationstatus'), nullable=False),
    sa.Column('output_path', sa.String(length=500), nullable=True),
    sa.Column('origin_probability_geometry', app.db.spatial.GeoJSONGeometry(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['spill_event_id'], ['spill_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_simulations_id'), 'drift_simulations', ['id'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spill_event_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'UNDER_REVIEW', 'HIGH_PRIORITY', 'RESOLVED', 'CLOSED', name='investigationstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spill_event_id'], ['spill_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spill_event_id')
    )
    op.create_index(op.f('ix_investigations_id'), 'investigations', ['id'], unique=False)
    op.create_index(op.f('ix_investigations_status'), 'investigations', ['status'], unique=False)
    op.create_table('spill_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spill_event_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mask_path', sa.String(length=500), nullable=True),
    sa.Column('polygon', app.db.spatial.GeoJSONGeometry(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['spill_event_id'], ['spill_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spill_detections_id'), 'spill_detections', ['id'], unique=False)
    op.create_table('vessel_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spill_event_id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('spatial_score', sa.Float(), nullable=False),
    sa.Column('temporal_score', sa.Float(), nullable=False),
    sa.Column('trajectory_score', sa.Float(), nullable=False),
    sa.Column('behaviour_score', sa.Float(), nullable=False),
    sa.Column('data_quality_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='prioritylevel'), nullable=False),
    sa.Column('explanation_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['spill_event_id'], ['spill_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_candidate_spill_overall', 'vessel_candidates', ['spill_event_id', 'overall_score'], unique=False)
    op.create_index(op.f('ix_vessel_candidates_id'), 'vessel_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_vessel_candidates_overall_score'), 'vessel_candidates', ['overall_score'], unique=False)
    op.create_index(op.f('ix_vessel_candidates_priority'), 'vessel_candidates', ['priority'], unique=False)
    op.create_index(op.f('ix_vessel_candidates_spill_event_id'), 'vessel_candidates', ['spill_event_id'], unique=False)
    op.create_index(op.f('ix_vessel_candidates_vessel_id'), 'vessel_candidates', ['vessel_id'], unique=False)
    op.create_table('drift_particles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('particle_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('position', app.db.spatial.GeoJSONGeometry(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['drift_simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_particles_id'), 'drift_particles', ['id'], unique=False)
    op.create_index(op.f('ix_drift_particles_particle_id'), 'drift_particles', ['particle_id'], unique=False)
    op.create_index(op.f('ix_drift_particles_timestamp'), 'drift_particles', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drift_particles_timestamp'), table_name='drift_particles')
    op.drop_index(op.f('ix_drift_particles_particle_id'), table_name='drift_particles')
    op.drop_index(op.f('ix_drift_particles_id'), table_name='drift_particles')
    op.drop_table('drift_particles')
    op.drop_index(op.f('ix_vessel_candidates_vessel_id'), table_name='vessel_candidates')
    op.drop_index(op.f('ix_vessel_candidates_spill_event_id'), table_name='vessel_candidates')
    op.drop_index(op.f('ix_vessel_candidates_priority'), table_name='vessel_candidates')
    op.drop_index(op.f('ix_vessel_candidates_overall_score'), table_name='vessel_candidates')
    op.drop_index(op.f('ix_vessel_candidates_id'), table_name='vessel_candidates')
    op.drop_index('idx_candidate_spill_overall', table_name='vessel_candidates')
    op.drop_table('vessel_candidates')
    op.drop_index(op.f('ix_spill_detections_id'), table_name='spill_detections')
    op.drop_table('spill_detections')
    op.drop_index(op.f('ix_investigations_status'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_drift_simulations_id'), table_name='drift_simulations')
    op.drop_table('drift_simulations')
    op.drop_index(op.f('ix_spill_events_status'), table_name='spill_events')
    op.drop_index(op.f('ix_spill_events_id'), table_name='spill_events')
    op.drop_index(op.f('ix_spill_events_detected_at'), table_name='spill_events')
    op.drop_table('spill_events')
    op.drop_index(op.f('ix_ais_positions_vessel_id'), table_name='ais_positions')
    op.drop_index(op.f('ix_ais_positions_timestamp'), table_name='ais_positions')
    op.drop_index(op.f('ix_ais_positions_id'), table_name='ais_positions')
    op.drop_index('idx_ais_vessel_timestamp', table_name='ais_positions')
    op.drop_index('idx_ais_timestamp', table_name='ais_positions')
    op.drop_table('ais_positions')
    op.drop_index(op.f('ix_vessels_mmsi'), table_name='vessels')
    op.drop_index(op.f('ix_vessels_imo'), table_name='vessels')
    op.drop_index(op.f('ix_vessels_id'), table_name='vessels')
    op.drop_table('vessels')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_satellite_images_product_id'), table_name='satellite_images')
    op.drop_index(op.f('ix_satellite_images_id'), table_name='satellite_images')
    op.drop_index(op.f('ix_satellite_images_acquisition_time'), table_name='satellite_images')
    op.drop_table('satellite_images')
    op.drop_index(op.f('ix_environmental_data_timestamp'), table_name='environmental_data')
    op.drop_index(op.f('ix_environmental_data_id'), table_name='environmental_data')
    op.drop_table('environmental_data')
    # ### end Alembic commands ###
